# Generated by Django 4.1.4 on 2023-01-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_transaction_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="product", new_name="order",
        ),
    ]
