# Generated by Django 4.1.4 on 2023-01-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_transaction_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
